import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Navbar from "./sections/Navbar";
import Footer from "./sections/Footer";

import AdminMenu from "@/components/AdminMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Upasana Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className} dark:bg-url('/texture-pattern-dark.svg') bg-url('/texture-pattern-light.svg')`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SignedIn>
              <AdminMenu />
            </SignedIn>
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
