/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/S80MEM665mu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function AboutSadhguruPage() {
  return (<>
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">John Doe</h1>
              <h2 className="text-xl font-medium text-gray-500 dark:text-gray-400">CEO, Acme Inc.</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                John Doe is the visionary leader behind Acme Inc., a thriving technology company that has
                revolutionized the industry with its innovative products and services.
              </p>
            </div>
          </div>
          <img
            alt="John Doe"
            className="mx-auto aspect-square overflow-hidden rounded-xl object-cover"
            height="550"
            src="/placeholder.svg"
            width="550" />
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Background</h2>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                John Doe has over 15 years of experience in the technology industry, having held various leadership
                roles at prominent companies before founding Acme Inc. He is known for his strategic vision,
                innovative thinking, and ability to build high-performing teams.
              </p>
            </div>
          </div>
          <img
            alt="John Doe Background"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            height="310"
            src="/placeholder.svg"
            width="550" />
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
          <img
            alt="John Doe Vision"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
            height="310"
            src="/placeholder.svg"
            width="550" />
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Vision</h2>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                John Doe's vision for Acme Inc. is to create a world-class technology company that empowers businesses
                and individuals to achieve their full potential. He is committed to driving innovation, fostering a
                culture of excellence, and delivering exceptional products and services that exceed customer
                expectations.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Accomplishments</h2>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Under John Doe's leadership, Acme Inc. has achieved remarkable success, including rapid growth,
                industry-leading innovation, and numerous awards and recognitions. He has been instrumental in
                building a talented and dedicated team, fostering a collaborative and inclusive culture, and driving
                the company's expansion into new markets.
              </p>
            </div>
          </div>
          <img
            alt="John Doe Accomplishments"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            height="310"
            src="/placeholder.svg"
            width="550" />
        </div>
      </div>
    </section>
  </>);
}
